-- customers (customer_id | customer_name | city )
-- orders ( order_id | Customer_id | product | amount | order_date )

-- 1. Get all the orders with the customer name 
      select o.order_id, c.customer_name, o.product  from orders o inner join customers c on c.customer_id= o. customer_id;

--2. get customers who have placed orders
        select distinct c.customer-name from customers c join orders o on c.customer_id= o. customer_id;

--3. Get customers who havve never placed orders
        select c.customer_name from customers c left join orders o on c.customer_id = o. customer_id where c.customer_id is null;

--4. Get all the customers and their orders
        select c.customer_name, o.order_id from customers c left join orders o on c.customer_id= o. customer_id;

--5. Get total numbers of orders per customer
        select c.customer_name , count(o.order_id) as total_orders from customers c left join orders o  on c.customer_id= o. customer_id group by c.customer_name;

--6. Get customers with more than 2 orders
        select c.customer_name, count(o.order_id) from total_orders from customers c join orders o on c.customer_id= o. customer_id group  by c.customer_name having total_order > 2;

--7. Get highest oorder amount per customer 
        select c.customer_name, max(o.amount ) as highest_amount from customers c join orders  o on  c.customer_id= o. customer_id group by c.customer_name;

--8. Get orders with customer city
        select o.order_id, o.amount, c.city from orders o join customers c on o c.customer_id= o. customer_id ;

--9. Get  customers who ordered the specific product
        select distinct c.customer_name from  customers c join orders o on  c.customer_id= o. customer_id  where o.product = '';

--10. Get customers who is not ordered from last 30 days
        select c.customer_name from customers c left join orders o on c.customer_id= o. customer_id and o.order_date >='2026-03-01' where order_id is null;

--11. Get customer with highest total spending
        select c.customer_name, sum(o.amount) as total_spend from c.customer_id join orders o on c.customer_id = o.order_id group by c.customer_name order by total_spent desc limit 1;

--12. Get all the orders even if customer data is missing
        select o.order_id, c.customer_name
        from customers c
        right join orders o
        on c. customer_id = o.order_id

--13. Get Number of orders per city
        select o.order_id, c.city, count(o.order_id) as total_orders 
        from customers c join orders o
        on c.customer_id = o.order_id
        group by c.city;

--14. Get customers who placed orders above the average amount
        select c.customer_name, o.order_id 
        from customers c join orders o 
        where o.amount > (select avg(amount) from orders);

--15. Get all orders with customers name and city
        select c.customer_name, o.order_id, c.city
        from order o 
        join customers c
        on c.customer_id=o.customer_id;

--16. Get Customers who placed at least one order above 5000
        select distinct c.customer_name, o.order_id 
        from customers c
        join orders o 
        on c.customer_id =o.customer_id
        where o.amount > 5000;

--17. Get customers who placed orders but only below  10000
         select distinct c.customer_name, o.order_id 
        from customers c
        join orders o 
        on c.customer_id =o.customer_id
        group by c.customer_name 
        having max( o.amount) < 10000

--18. Get customers and their latest order data
        select c.customer_name, max(o.order_date) as last_order
        from customers c
        join orders o 
        on c.customer_id =o.customer_id
        group by c.customer_name;

--19.Get customers with exactly 1 order
        select c.customer_name from customer c
        join orders o 
         on c.customer_id =o.customer_id
        group by c.customer_name 
        having count(o.order_id)=1

--20. Get customers who placed ordered multiple products
        select c.customer_name from customer c
        join orders o 
         on c.customer_id =o.customer_id
        group by c.customer_name 
        having count(distinct o.product)>1;

--21. GEt highest order per city
        select c.customer_name, max(o.amount) as highest_order, c.city from customer c
        join orders o 
         on c.customer_id =o.customer_id
        group by c.city;

--22. Get customrs who neve ordered a mobile
        select c.customer_name, o.order_id, o.product
        from customers c
        left join orders o         
        on c.customer_id =o.customer_id
        and o.product = "Mobile"
        where o.order_id is null;

--23. Get total reveue generated by city
        select c.customer_name, total(o.amount) as highest_order, c.city from customer c
        join orders o 
        on c.customer_id =o.customer_id
        group by c.city;

--24. Get customers who places orders on multipple days
        select c.customer_name from customer c
        join orders o 
         on c.customer_id =o.customer_id
        group by c.customer_name 
        having count(distinct o.order_date)>1;

--25. Get customers whose all orders are above 20000
        select c.customer_name,  from customer c
        join orders o 
         on c.customer_id =o.customer_id
        group by c.customer_name 
        having min(o.amount)>2000;
        
